import { STAGE_RENDER_DEPTH } from '../config.js';
import { PARTICLE_TEXTURES } from '../world/ParticleTextureFactory.js';
import { PARTICLE_SEMANTIC_COLORS } from '../world/ParticleColors.js';

export const PARTICLE_PROFILES = Object.freeze({
    player: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'NORMAL',
        depth: STAGE_RENDER_DEPTH.actors,
        category: 'actor',
        maxAlive: 180,
        form: Object.freeze({ zone: 'circleEdge', radius: 18, quantity: 16 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 650, max: 950 }),
            speed: Object.freeze({ min: 6, max: 18 }),
            scale: Object.freeze({ start: 0.55, end: 0.05 }),
            alpha: Object.freeze({ start: 0.72, end: 0 }),
            frequency: 34,
            quantity: 2,
            rotate: Object.freeze({ min: -18, max: 18 }),
        }),
        tint: Object.freeze({ mode: 'zone', colors: Object.freeze(['base', 'accent']) }),
        modifiers: Object.freeze({
            low_hp: Object.freeze({
                frequency: 20,
                quantity: 3,
                alpha: Object.freeze({ start: 0.9, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
            }),
            staggered: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                frequency: 14,
                quantity: 3,
                speed: Object.freeze({ min: 18, max: 60 }),
                alpha: Object.freeze({ start: 0.9, end: 0 }),
            }),
            dashing: Object.freeze({
                frequency: 12,
                quantity: 4,
                speed: Object.freeze({ min: 28, max: 72 }),
                alpha: Object.freeze({ start: 0.86, end: 0 }),
            }),
            controlled: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.CONTROLLED,
                frequency: 26,
            }),
        }),
        bursts: Object.freeze({
            damaged: Object.freeze({
                quantity: 24,
                lifespan: Object.freeze({ min: 120, max: 220 }),
                speed: Object.freeze({ min: 45, max: 170 }),
                scale: Object.freeze({ start: 1.25, end: 0 }),
                alpha: Object.freeze({ start: 1, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                blendMode: 'ADD',
            }),
            death: Object.freeze({
                quantity: 70,
                lifespan: Object.freeze({ min: 420, max: 760 }),
                speed: Object.freeze({ min: 35, max: 210 }),
                scale: Object.freeze({ start: 0.9, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DEATH,
                blendMode: 'ADD',
            }),
            flinch: Object.freeze({
                quantity: 12,
                lifespan: Object.freeze({ min: 80, max: 140 }),
                speed: Object.freeze({ min: 70, max: 150 }),
                scale: Object.freeze({ start: 0.9, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE_FLASH,
                blendMode: 'ADD',
            }),
        }),
    }),
    zombie: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'NORMAL',
        depth: STAGE_RENDER_DEPTH.actors,
        category: 'actor',
        maxAlive: 120,
        form: Object.freeze({ zone: 'circleEdge', radius: 19, quantity: 12 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 850, max: 1350 }),
            speed: Object.freeze({ min: 3, max: 15 }),
            scale: Object.freeze({ start: 0.48, end: 0.02 }),
            alpha: Object.freeze({ start: 0.55, end: 0 }),
            frequency: 58,
            quantity: 2,
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([0x7da06f, 0xb999ff]) }),
        modifiers: Object.freeze({
            hostile: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.HOSTILE,
                frequency: 26,
                quantity: 3,
                alpha: Object.freeze({ start: 0.75, end: 0 }),
            }),
            low_hp: Object.freeze({
                frequency: 34,
                speed: Object.freeze({ min: 12, max: 44 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
            }),
            staggered: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                frequency: 14,
                quantity: 3,
                speed: Object.freeze({ min: 22, max: 65 }),
                alpha: Object.freeze({ start: 0.88, end: 0 }),
            }),
        }),
        bursts: Object.freeze({
            damaged: Object.freeze({
                quantity: 20,
                lifespan: Object.freeze({ min: 110, max: 220 }),
                speed: Object.freeze({ min: 55, max: 180 }),
                scale: Object.freeze({ start: 1.15, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                blendMode: 'ADD',
            }),
            death: Object.freeze({
                quantity: 58,
                lifespan: Object.freeze({ min: 500, max: 900 }),
                speed: Object.freeze({ min: 30, max: 190 }),
                scale: Object.freeze({ start: 0.75, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DEATH,
                blendMode: 'ADD',
            }),
            flinch: Object.freeze({
                quantity: 10,
                lifespan: 110,
                speed: Object.freeze({ min: 60, max: 150 }),
                scale: Object.freeze({ start: 0.85, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE_FLASH,
                blendMode: 'ADD',
            }),
        }),
    }),
    golem: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'NORMAL',
        depth: STAGE_RENDER_DEPTH.actors,
        category: 'actor',
        maxAlive: 140,
        form: Object.freeze({ zone: 'circleFill', radius: 21 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 900, max: 1500 }),
            speed: Object.freeze({ min: 1, max: 8 }),
            scale: Object.freeze({ start: 0.62, end: 0.08 }),
            alpha: Object.freeze({ start: 0.62, end: 0 }),
            frequency: 48,
            quantity: 2,
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([0x8f96a3, 0xc2c7d1]) }),
        modifiers: Object.freeze({
            possessed: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.POSSESSED,
                frequency: 26,
                quantity: 3,
            }),
            controlled: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.CONTROLLED,
                frequency: 30,
            }),
            low_hp: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                frequency: 30,
            }),
            staggered: Object.freeze({
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                frequency: 16,
                quantity: 3,
                speed: Object.freeze({ min: 14, max: 48 }),
                alpha: Object.freeze({ start: 0.85, end: 0 }),
            }),
        }),
        bursts: Object.freeze({
            damaged: Object.freeze({
                quantity: 26,
                lifespan: Object.freeze({ min: 160, max: 320 }),
                speed: Object.freeze({ min: 25, max: 130 }),
                scale: Object.freeze({ start: 1.2, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE,
                blendMode: 'ADD',
            }),
            death: Object.freeze({
                quantity: 76,
                lifespan: Object.freeze({ min: 650, max: 1100 }),
                speed: Object.freeze({ min: 20, max: 150 }),
                scale: Object.freeze({ start: 0.95, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DEATH,
                blendMode: 'ADD',
            }),
            flinch: Object.freeze({
                quantity: 12,
                lifespan: 150,
                speed: Object.freeze({ min: 30, max: 110 }),
                scale: Object.freeze({ start: 0.9, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DAMAGE_FLASH,
                blendMode: 'ADD',
            }),
        }),
    }),
    corpse: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'NORMAL',
        depth: STAGE_RENDER_DEPTH.actors,
        category: 'actor',
        maxAlive: 70,
        form: Object.freeze({ zone: 'circleFill', radius: 14 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 1200, max: 2200 }),
            speed: Object.freeze({ min: 2, max: 12 }),
            scale: Object.freeze({ start: 0.35, end: 0 }),
            alpha: Object.freeze({ start: 0.32, end: 0 }),
            frequency: 120,
            quantity: 1,
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([0x6c5678, 0x393042]) }),
        modifiers: Object.freeze({}),
        bursts: Object.freeze({
            death: Object.freeze({
                quantity: 36,
                lifespan: Object.freeze({ min: 600, max: 1000 }),
                speed: Object.freeze({ min: 20, max: 120 }),
                scale: Object.freeze({ start: 0.6, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.DEATH,
                blendMode: 'ADD',
            }),
        }),
    }),
    bullet: Object.freeze({
        texture: PARTICLE_TEXTURES.streak,
        blendMode: 'ADD',
        depth: STAGE_RENDER_DEPTH.actors + 1,
        category: 'projectile',
        maxAlive: 70,
        form: Object.freeze({ zone: 'point' }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 100, max: 180 }),
            speed: Object.freeze({ min: 0, max: 12 }),
            scale: Object.freeze({ start: 0.42, end: 0 }),
            alpha: Object.freeze({ start: 0.85, end: 0 }),
            frequency: 18,
            quantity: 1,
            tint: 0xffa75c,
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([0xffa75c]) }),
        modifiers: Object.freeze({}),
        bursts: Object.freeze({}),
    }),
    arrow: Object.freeze({
        texture: PARTICLE_TEXTURES.streak,
        blendMode: 'ADD',
        depth: STAGE_RENDER_DEPTH.actors + 1,
        category: 'projectile',
        maxAlive: 80,
        form: Object.freeze({ zone: 'point' }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 130, max: 240 }),
            speed: Object.freeze({ min: 0, max: 8 }),
            scale: Object.freeze({ start: 0.32, end: 0 }),
            alpha: Object.freeze({ start: 0.72, end: 0 }),
            frequency: 20,
            quantity: 1,
            tint: 0xf5d87c,
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([0xf5d87c]) }),
        modifiers: Object.freeze({}),
        bursts: Object.freeze({}),
    }),
    loot: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'ADD',
        depth: STAGE_RENDER_DEPTH.interactables,
        category: 'interactable',
        maxAlive: 90,
        form: Object.freeze({ zone: 'circleEdge', radius: 12, quantity: 10 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 500, max: 850 }),
            speed: Object.freeze({ min: 2, max: 16 }),
            scale: Object.freeze({ start: 0.48, end: 0 }),
            alpha: Object.freeze({ start: 0.9, end: 0 }),
            frequency: 42,
            quantity: 2,
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([PARTICLE_SEMANTIC_COLORS.QUEST, 0xffffff]) }),
        modifiers: Object.freeze({}),
        bursts: Object.freeze({}),
    }),
    warm_fire: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'ADD',
        depth: STAGE_RENDER_DEPTH.interactables,
        category: 'interactable',
        maxAlive: 120,
        form: Object.freeze({ zone: 'circleFill', radius: 16 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 520, max: 900 }),
            speedY: Object.freeze({ min: -38, max: -12 }),
            speedX: Object.freeze({ min: -10, max: 10 }),
            scale: Object.freeze({ start: 0.62, end: 0 }),
            alpha: Object.freeze({ start: 0.88, end: 0 }),
            frequency: 34,
            quantity: 2,
            tint: Object.freeze([0xffb45f, 0xffe0a3]),
        }),
        tint: Object.freeze({ mode: 'fixed', colors: Object.freeze([0xffb45f, 0xffe0a3]) }),
        modifiers: Object.freeze({}),
        bursts: Object.freeze({
            cleanse: Object.freeze({
                quantity: 80,
                lifespan: Object.freeze({ min: 350, max: 800 }),
                speed: Object.freeze({ min: 20, max: 190 }),
                scale: Object.freeze({ start: 1.1, end: 0 }),
                tint: PARTICLE_SEMANTIC_COLORS.SAFE,
                blendMode: 'ADD',
            }),
        }),
    }),
    exit: Object.freeze({
        texture: PARTICLE_TEXTURES.soft,
        blendMode: 'ADD',
        depth: STAGE_RENDER_DEPTH.exits,
        category: 'interactable',
        maxAlive: 150,
        form: Object.freeze({ zone: 'circleEdge', radius: 28, quantity: 20 }),
        emitter: Object.freeze({
            lifespan: Object.freeze({ min: 700, max: 1200 }),
            speed: Object.freeze({ min: 4, max: 24 }),
            scale: Object.freeze({ start: 0.55, end: 0.02 }),
            alpha: Object.freeze({ start: 0.7, end: 0 }),
            frequency: 28,
            quantity: 2,
            rotate: Object.freeze({ min: -45, max: 45 }),
        }),
        tint: Object.freeze({ mode: 'zone', colors: Object.freeze(['accent', 'base']) }),
        modifiers: Object.freeze({}),
        bursts: Object.freeze({}),
    }),
});
