export const PARTICLE_SEMANTIC_COLORS = Object.freeze({
    HOSTILE: 0xcc2222,
    QUEST: 0xf5d87c,
    INTERACTABLE_NPC: 0x4dd4c0,
    DAMAGE_FLASH: 0xffffff,
    DAMAGE: 0xd23558,
    DEATH: 0x6633aa,
    CONTROLLED: 0x9ee7ff,
    POSSESSED: 0xb18cff,
    SAFE: 0xd9b66f,
});

export const DEFAULT_ZONE_PALETTE = Object.freeze({
    base: 0xa8c5c2,
    accent: 0x8e84b7,
    shadow: 0x1e2a4a,
    deep: 0x11182c,
    surface: 0x294a6e,
    light: 0xeaf2f7,
    threshold: 0xf0b65a,
    ambientDensity: 90,
    ambientDrift: Object.freeze({ x: -4, y: -2 }),
    ambientTexture: 'particle-soft',
    ambientAlpha: 0.055,
    ambientScale: 0.22,
    spiritualForce: 'veil-current',
});

export const ZONE_PARTICLE_PALETTES = Object.freeze({
    lunavik: Object.freeze({
        base: 0xcfd7ff,
        accent: 0x4dd4c0,
        shadow: 0x101723,
        ambientDensity: 120,
        ambientDrift: Object.freeze({ x: 1, y: -5 }),
        ambientTexture: 'particle-dot',
    }),
    'western-wilds': Object.freeze({
        base: 0x94b884,
        accent: 0xb999ff,
        shadow: 0x121a14,
        ambientDensity: 130,
        ambientDrift: Object.freeze({ x: -2, y: -4 }),
        ambientTexture: 'particle-dot',
    }),
    'great-northern-road': Object.freeze({
        base: 0xa8c5c2,
        accent: 0x8e84b7,
        shadow: 0x1e2a4a,
        deep: 0x11182c,
        surface: 0x294a6e,
        light: 0xeaf2f7,
        threshold: 0xf0b65a,
        ambientDensity: 80,
        ambientDrift: Object.freeze({ x: -6, y: -1 }),
        ambientTexture: 'particle-soft',
        ambientAlpha: 0.045,
        ambientScale: 0.2,
        spiritualForce: 'veil-current',
    }),
    'the-meadows': Object.freeze({
        base: 0x9ed7a6,
        accent: 0xd3a8ff,
        shadow: 0x152216,
        ambientDensity: 150,
        ambientDrift: Object.freeze({ x: 2, y: -4 }),
        ambientTexture: 'particle-dot',
    }),
    'the-grotto': Object.freeze({
        base: 0x5fd6d1,
        accent: 0x7d8cff,
        shadow: 0x0d1024,
        ambientDensity: 130,
        ambientDrift: Object.freeze({ x: 0, y: -3 }),
        ambientTexture: 'particle-soft',
    }),
    'the-misty-path': Object.freeze({
        base: 0xb7c7db,
        accent: 0xc7a7ff,
        shadow: 0x111821,
        ambientDensity: 140,
        ambientDrift: Object.freeze({ x: -1, y: -6 }),
        ambientTexture: 'particle-soft',
    }),
    'rolling-hills': Object.freeze({
        base: 0xb8d49b,
        accent: 0x9fc7ff,
        shadow: 0x172115,
        ambientDensity: 130,
        ambientDrift: Object.freeze({ x: 2, y: -5 }),
        ambientTexture: 'particle-dot',
    }),
});
